POST http://localhost:3006/api/user/register
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "pass123QWE"
}

###
PUT http://localhost:3006/api/user/validation
Content-Type: application/json
authoritation: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RlYTJkY2U5MTVjMzZjYjM2ODIxZjYiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjY0MzkzMiwiZXhwIjoxNzQyNjUxMTMyfQ.ksxgBoTQTFALv_0-eC5uCoIGT71odBTuOnBIJWtgWUk

{
    "code": "456258"
}

###
POST http://localhost:3006/api/user/login
Content-Type: application/json

{
    "email": "alv_lau@gmail.com",
    "password": "pass123QWE"
}

###
PUT http://localhost:3006/api/user/register
Content-Type: application/json
authoritation: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RlYTI4NjZkMzJhZWYxYmM3YzM4MGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjY0Mzg0NiwiZXhwIjoxNzQyNjUxMDQ2fQ.JhdKwFL1Qni6OvtIT2t2kvjkKb6tbox-y1xDBkYuJEI

{
    "email": "lau@gmail.com",
    "name" : "laura",
    "surnames" : "alvarez perez",
    "nif": "785421693J"
}

###
PATCH http://localhost:3006/api/user/company
Content-Type: application/json
authoritation: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RlYTBhYWVmZGJiMjUzYWM4YzZmNGQiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjY0MzM3MCwiZXhwIjoxNzQyNjUwNTcwfQ.fVqSM1kg60L8MklIYolv08tb6Wtumg4R9DQp2FJXE8o

{
    "company":{
        "cif":"741412963L",
        "name": "u-tad",
        "street": "las rozas",
        "province": "madrid",
        "number": 3,
        "postal": 12345,
        "city": "madrid"
    }
}

###

PATCH http://localhost:3006/api/user/logo
authoritation: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RkODIxNTQyMWNkMTYzYTA5Y2RiZmYiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjU3MDAwNSwiZXhwIjoxNzQyNTc3MjA1fQ.dknjOAVKEHM6dMPBmXua9usXmZkjkMkON6LQYQLJapA
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="bici.jpg"
Content-Type: image/jpeg

< ./bici.jpg
--boundary123--


###
GET http://localhost:3006/api/user
authoritation: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RkNzViNTBiM2NhZWM3YzZlNThjNzYiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjYzODY3OCwiZXhwIjoxNzQyNjQ1ODc4fQ.TFM8on-Iv-d168qa1lpENMmJNh3_HYdKWgtbvrYwBZw

###
DELETE http://localhost:3006/api/user?soft=false
authoritation: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RlOTY5OTE5ODA0OTFmYzQzMzk3OTQiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjY0MDc5MywiZXhwIjoxNzQyNjQ3OTkzfQ.jyHcyG2cZu5OEIwzqh1ETQETaKTD4EyKtC_KFgm_yu0


###
POST http://localhost:3006/api/user/invite
Content-Type: application/json
authoritation: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RlYTBhYWVmZGJiMjUzYWM4YzZmNGQiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjY0MzM3MCwiZXhwIjoxNzQyNjUwNTcwfQ.fVqSM1kg60L8MklIYolv08tb6Wtumg4R9DQp2FJXE8o

{
    "email": "maria@gmail.com",
    "name" : "maría",
    "surnames" : "perez"
}
